[auth]
redirect_uri = "https://youtubedownloader-fkrgtexwva2yh4b4fcywsj.streamlit.app/"  # 本番はデプロイ先URLに変更
cookie_secret = "ランダムな長い文字列"
client_id = "取得したクライアントID"
client_secret = "取得したクライアントシークレット"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"  # Googleの場合
